version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - type: volume
        source: public-content
        target: /var/www/nmebious/static
        volume:
          nocopy: true
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    ports:
      - "4005:4005"
      - "8080:8080"
    volumes:
      - public-content:/usr/src/app/public

volumes:
  public-content:
