version: "3.7"
services: 
  db:
    build:
      context: .
      dockerfile: docker/db.docker
    env_file: .env
  app:
    build:
      context: .
      dockerfile: docker/app.docker
    depends_on:
      - db
    ports:
      - "4005:4005"
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /nmebious
