version: "3"
services: 
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    ports:
      - "4005:4005"
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /nmebious
