version: "3.8"

x-common-variables: &common-variables
  DOCKER_RUNNING: "true"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    logging:
      driver: "local"
    volumes:
      - type: volume
        source: public-content
        target: /var/www/nmebious/static
        volume:
          nocopy: true
    environment:
      <<: *common-variables
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    logging:
      driver: "local"
    environment:
      <<: *common-variables
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    ports:
      - "4005:4005"
      - "8080:8080"
    logging:
      driver: "local"
    volumes:
      - public-content:/usr/src/app/public
    env_file:
      - ./.env
    environment:
      - DB_HOST=db

volumes:
  public-content:
